name: CI
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        id: setup-go
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            go.sum
      - run: go mod download
      - name: build
        run: go build -o ./a ./
      - name: test
        run: go test -race ./...
      - name: generate image
        run: |
          ./a -i ./examples/monalisa.png -o ./out.svg -n 50
      - name: preview generated image
        run: |
          echo '# from monalisa.png' >> "$GITHUB_STEP_SUMMARY"
          echo                       >> "$GITHUB_STEP_SUMMARY"
          cat ./out.svg              >> "$GITHUB_STEP_SUMMARY"
      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.8
      - name: golangci-lint
        env:
          _go_version: ${{ steps.setup-go.outputs.go-version }}
        run: |
          golangci-lint run \
            --output.text.path stdout \
            --output.text.print-issued-lines \
            --issues-exit-code 0 \
            --config .golangci.yml \
            1>lint-stdout.txt 2>/dev/stderr
      - name: reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          reviewdog \
            -name golangci-lint \
            -f golangci-lint \
            -filter-mode nofilter \
            -reporter github-pr-check \
            -fail-level error \
            < lint-stdout.txt
