name: CI
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        id: setup-go
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            go.sum
      - run: go mod download
      - name: build
        run: go build -o /dev/null ./
      - name: test
        run: go test -race ./...
